# Generated by Django 3.2.13 on 2023-09-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MinhaTabela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=100)),
                ('so', models.CharField(max_length=100)),
                ('processadsor', models.CharField(max_length=100)),
                ('memoria', models.CharField(max_length=100)),
                ('placa_de_video', models.CharField(max_length=100)),
                ('directx', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='motivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('mecanica', models.CharField(max_length=70)),
                ('concorda', models.CharField(choices=[('B', 'Bastante'), ('M', 'mais ou menos'), ('P', 'Pouco')], default='', max_length=1)),
                ('ja_jogou', models.CharField(choices=[('Y', 'SIM'), ('N', 'NÃO')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='sensações',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('dificuldade', models.CharField(choices=[('H', 'high'), ('M', 'Medium,'), ('L', 'low')], max_length=1)),
                ('fez', models.CharField(choices=[('Y', 'SIM'), ('N', 'NÃO')], max_length=1)),
                ('prazer', models.CharField(choices=[('H', 'high'), ('M', 'Medium,'), ('L', 'low')], max_length=1)),
            ],
        ),
    ]
